
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int virgu = 18;
  public static final int CADENA = 16;
  public static final int llaveIzq = 8;
  public static final int coma = 15;
  public static final int llaveDer = 9;
  public static final int porcentaje = 7;
  public static final int ID = 20;
  public static final int CARACTER = 17;
  public static final int menos = 5;
  public static final int punto = 14;
  public static final int ptcoma = 3;
  public static final int EOF = 0;
  public static final int CONJ = 2;
  public static final int pleca = 13;
  public static final int error = 1;
  public static final int ASCII = 19;
  public static final int asterisco = 12;
  public static final int mas = 10;
  public static final int interrogacion = 11;
  public static final int dospuntos = 4;
  public static final int mayor = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "ptcoma",
  "dospuntos",
  "menos",
  "mayor",
  "porcentaje",
  "llaveIzq",
  "llaveDer",
  "mas",
  "interrogacion",
  "asterisco",
  "pleca",
  "punto",
  "coma",
  "CADENA",
  "CARACTER",
  "virgu",
  "ASCII",
  "ID"
  };
}

